changelog:
  categories:
    - title: "New Features"
      labels:
        - "feat"
        - "enhancement"
    - title: "Bug Fixes"
      labels:
        - "fix"
        - "bug"
    - title: "Refactors"
      labels:
        - "refactor"
    - title: "Maintenance"
      labels:
        - "chore"
        - "docs"
        - "test"
  exclude:
    labels:
      - "skip-changelog"
