import { useMemo } from "react";
export type {
  StaticFretboardTopologyNote,
  UseStaticFretboardTopologyProps,
} from "./buildStaticFretboardTopology";
export { buildStaticFretboardTopology } from "./buildStaticFretboardTopology";
import {
  buildStaticFretboardTopology,
  type StaticFretboardTopologyNote,
  type UseStaticFretboardTopologyProps,
} from "./buildStaticFretboardTopology";

export function useStaticFretboardTopology(
  props: UseStaticFretboardTopologyProps,
): StaticFretboardTopologyNote[] {
  const {
    numStrings,
    fretboardLayout,
    totalColumns,
    startFret,
    maxFret,
    hiddenNotes,
    highlightNotes,
    hasChordOverlay,
    chordTones,
    rootNote,
    chordRoot,
    colorNotes,
    shapePolygons,
    chordFretSpread,
    activePattern,
    shapeScope,
    activeShape,
    scaleName,
    preferFlats,
    displayFormat,
    wrappedNotes,
    tuning,
    noteSemantics,
    fullChordPositionKeys,
    fullChordShapeByPosition,
    chordBoxBounds,
  } = props;

  return useMemo(() => buildStaticFretboardTopology({
    numStrings,
    fretboardLayout,
    totalColumns,
    startFret,
    maxFret,
    hiddenNotes,
    highlightNotes,
    hasChordOverlay,
    chordTones,
    rootNote,
    chordRoot,
    colorNotes,
    shapePolygons,
    chordFretSpread,
    activePattern,
    shapeScope,
    activeShape,
    scaleName,
    preferFlats,
    displayFormat,
    wrappedNotes,
    tuning,
    noteSemantics,
    fullChordPositionKeys,
    fullChordShapeByPosition,
    chordBoxBounds,
  }), [
    numStrings,
    fretboardLayout,
    totalColumns,
    startFret,
    maxFret,
    hiddenNotes,
    highlightNotes,
    hasChordOverlay,
    chordTones,
    rootNote,
    chordRoot,
    colorNotes,
    shapePolygons,
    chordFretSpread,
    activePattern,
    shapeScope,
    activeShape,
    scaleName,
    preferFlats,
    displayFormat,
    wrappedNotes,
    tuning,
    noteSemantics,
    fullChordPositionKeys,
    fullChordShapeByPosition,
    chordBoxBounds,
  ]);
}
