/**
 * Audit: identifies FULL_CHORD_TEMPLATES entries that are pitch-and-position
 * identical to a generated close voicing across all 12 roots.
 *
 * Run:
 *   ./node_modules/.bin/vite-node --options.deps.inline="/@tonaljs/" \
 *     scripts/audit-full-close-overlap.ts \
 *     > docs/superpowers/research/2026-05-26-full-close-voicing-overlap.md
 *
 * NOTE: Run via vite-node (not node/tsx) because @tonaljs packages require
 * bundler-style ESM resolution and do not resolve under plain Node ESM.
 * The `deps.inline=/@tonaljs/` flag forces Vite to transform tonal packages
 * through its bundler (they're CJS-style under the hood despite shipping .mjs).
 *
 * Output is markdown — paste-ready for the research doc. The script emits a
 * top-level title and a `<REPLACE-WITH-HEAD-SHA>` placeholder; replace it
 * with the current git HEAD SHA before committing the report.
 */
import { NOTES } from "../packages/core/src/theory";
import { STANDARD_TUNING } from "../packages/core/src/guitar";
import { generateVoicings } from "../packages/core/src/shapes/voicings";
import type { Voicing } from "../packages/core/src/shapes/voicings";
import { FULL_CHORD_TEMPLATES } from "../packages/core/src/shapes/templates";

const MAX_FRET = 24;
const ROOTS = NOTES; // 12 chromatic roots, sharps

/** Normalize a voicing to a frets-relative shape signature.
 *  Anchor: subtract the minimum fretted fret from every note. Returns a sorted
 *  "stringIndex:relativeFret" string. Open strings (fret 0) anchor to 0.
 */
function shapeSignature(v: Voicing): string {
  const fretted = v.notes.filter((n) => n.fretIndex > 0).map((n) => n.fretIndex);
  const anchor = fretted.length > 0 ? Math.min(...fretted) : 0;
  return v.notes
    .map((n) => `${n.stringIndex}:${n.fretIndex === 0 ? 0 : n.fretIndex - anchor}`)
    .sort()
    .join(",");
}

interface OverlapRow {
  shape: string;
  templateFrets: string;
  hasCloseEquivalent: boolean;
  stringSet: string;
}

function auditQuality(chordType: string): OverlapRow[] {
  const rows: OverlapRow[] = [];
  const templatesForQuality = FULL_CHORD_TEMPLATES.filter((t) => t.quality === chordType);

  for (const template of templatesForQuality) {
    let identicalForAllRoots = true;
    let stringSet = "";

    for (const root of ROOTS) {
      const fulls = generateVoicings({
        chordRoot: root,
        chordType,
        tuning: STANDARD_TUNING,
        maxFret: MAX_FRET,
        voicingType: "full",
      }).filter((v) => v.shape === template.shape);

      const closes = generateVoicings({
        chordRoot: root,
        chordType,
        tuning: STANDARD_TUNING,
        maxFret: MAX_FRET,
        voicingType: "close",
      });

      if (fulls.length === 0) {
        identicalForAllRoots = false;
        break;
      }

      const closeSigs = new Set(closes.map(shapeSignature));
      const matched = fulls.some((f) => closeSigs.has(shapeSignature(f)));
      if (!matched) {
        identicalForAllRoots = false;
        break;
      }

      // Capture string set from the first matching full voicing for reporting.
      if (stringSet === "") {
        const f = fulls[0];
        stringSet = f.notes.map((n) => n.stringIndex).sort().join(",");
      }
    }

    rows.push({
      shape: template.shape,
      templateFrets: JSON.stringify(template.fretsHighToLow),
      hasCloseEquivalent: identicalForAllRoots,
      stringSet,
    });
  }

  return rows;
}

function emitReport(): void {
  const qualities = Array.from(new Set(FULL_CHORD_TEMPLATES.map((t) => t.quality))).sort();

  console.log("# Full / Close Voicing Overlap Audit");
  console.log("");
  console.log("> Generated by `scripts/audit-full-close-overlap.ts` at commit `<REPLACE-WITH-HEAD-SHA>`.");
  console.log("");
  console.log("Identifies `FULL_CHORD_TEMPLATES` entries that are pitch-and-position identical to a generated close voicing (after fret-anchor normalization) across all 12 chromatic roots. Identical entries are cosmetic duplicates and candidates for deletion.");
  console.log("");

  const deletionCandidates: string[] = [];
  for (const quality of qualities) {
    console.log(`## ${quality}`);
    console.log("");
    console.log("| CAGED shape | Template fretsHighToLow | Close equivalent? | String set |");
    console.log("|---|---|---|---|");
    const rows = auditQuality(quality);
    for (const row of rows) {
      console.log(`| ${row.shape} | \`${row.templateFrets}\` | ${row.hasCloseEquivalent ? "yes" : "no"} | ${row.stringSet || "—"} |`);
      if (row.hasCloseEquivalent) {
        deletionCandidates.push(`- ${quality} / ${row.shape}-shape — \`${row.templateFrets}\``);
      }
    }
    console.log("");
  }

  console.log("## Deletion candidates");
  console.log("");
  if (deletionCandidates.length === 0) {
    console.log("_None — every full template has at least one root where it is not exactly a close voicing._");
  } else {
    for (const c of deletionCandidates) console.log(c);
  }
  console.log("");
  console.log("## Appendix — script");
  console.log("");
  console.log("Source: `scripts/audit-full-close-overlap.ts` in the same commit as this report.");
}

emitReport();
