/**
 * Audit: identifies FULL_CHORD_TEMPLATES entries that are pitch-and-position
 * identical to a generated close voicing across all 12 roots.
 *
 * Run:  node_modules/.bin/vitest run --config scripts/vitest.audit.config.ts
 *
 * NOTE: This script is executed via vitest (which uses Vite under the hood)
 * because @tonaljs packages require bundler-style ESM resolution and do not
 * resolve correctly under plain Node ESM (tsx/node directly).
 *
 * The script writes the markdown report directly to:
 *   docs/superpowers/research/2026-05-26-full-close-voicing-overlap.md
 *
 * After running, replace the <REPLACE-WITH-HEAD-SHA> placeholder with the
 * current git HEAD SHA before committing the report.
 */
import { it } from "vitest";
import { NOTES } from "../packages/core/src/theory";
import { STANDARD_TUNING } from "../packages/core/src/guitar";
import { generateVoicings } from "../packages/core/src/shapes/voicings";
import type { Voicing } from "../packages/core/src/shapes/voicings";
import { FULL_CHORD_TEMPLATES } from "../packages/core/src/shapes/templates";

const MAX_FRET = 24;
const ROOTS = NOTES; // 12 chromatic roots, sharps

/** Normalize a voicing to a frets-relative shape signature.
 *  Anchor: subtract the minimum fretted fret from every note. Returns a sorted
 *  "stringIndex:relativeFret" string. Open strings (fret 0) anchor to 0.
 */
function shapeSignature(v: Voicing): string {
  const fretted = v.notes.filter((n) => n.fretIndex > 0).map((n) => n.fretIndex);
  const anchor = fretted.length > 0 ? Math.min(...fretted) : 0;
  return v.notes
    .map((n) => `${n.stringIndex}:${n.fretIndex === 0 ? 0 : n.fretIndex - anchor}`)
    .sort()
    .join(",");
}

interface OverlapRow {
  shape: string;
  templateFrets: string;
  hasCloseEquivalent: boolean;
  stringSet: string;
}

function auditQuality(chordType: string): OverlapRow[] {
  const rows: OverlapRow[] = [];
  const templatesForQuality = FULL_CHORD_TEMPLATES.filter((t) => t.quality === chordType);

  for (const template of templatesForQuality) {
    let identicalForAllRoots = true;
    let stringSet = "";

    for (const root of ROOTS) {
      const fulls = generateVoicings({
        chordRoot: root,
        chordType,
        tuning: STANDARD_TUNING,
        maxFret: MAX_FRET,
        voicingType: "full",
      }).filter((v) => v.shape === template.shape);

      const closes = generateVoicings({
        chordRoot: root,
        chordType,
        tuning: STANDARD_TUNING,
        maxFret: MAX_FRET,
        voicingType: "close",
      });

      if (fulls.length === 0) {
        identicalForAllRoots = false;
        break;
      }

      const closeSigs = new Set(closes.map(shapeSignature));
      const matched = fulls.some((f) => closeSigs.has(shapeSignature(f)));
      if (!matched) {
        identicalForAllRoots = false;
        break;
      }

      // Capture string set from the first matching full voicing for reporting.
      if (stringSet === "") {
        const f = fulls[0];
        stringSet = f.notes.map((n) => n.stringIndex).sort().join(",");
      }
    }

    rows.push({
      shape: template.shape,
      templateFrets: JSON.stringify(template.fretsHighToLow),
      hasCloseEquivalent: identicalForAllRoots,
      stringSet,
    });
  }

  return rows;
}

function buildReport(): string {
  const qualities = Array.from(new Set(FULL_CHORD_TEMPLATES.map((t) => t.quality))).sort();
  const lines: string[] = [];

  lines.push("# Full / Close Voicing Overlap Audit");
  lines.push("");
  lines.push("> Generated by `scripts/audit-full-close-overlap.ts` at commit `<REPLACE-WITH-HEAD-SHA>`.");
  lines.push("");
  lines.push("Identifies `FULL_CHORD_TEMPLATES` entries that are pitch-and-position identical to a generated close voicing (after fret-anchor normalization) across all 12 chromatic roots. Identical entries are cosmetic duplicates and candidates for deletion.");
  lines.push("");

  const deletionCandidates: string[] = [];
  for (const quality of qualities) {
    lines.push(`## ${quality}`);
    lines.push("");
    lines.push("| CAGED shape | Template fretsHighToLow | Close equivalent? | String set |");
    lines.push("|---|---|---|---|");
    const rows = auditQuality(quality);
    for (const row of rows) {
      lines.push(`| ${row.shape} | \`${row.templateFrets}\` | ${row.hasCloseEquivalent ? "yes" : "no"} | ${row.stringSet || "—"} |`);
      if (row.hasCloseEquivalent) {
        deletionCandidates.push(`- ${quality} / ${row.shape}-shape — \`${row.templateFrets}\``);
      }
    }
    lines.push("");
  }

  lines.push("## Deletion candidates");
  lines.push("");
  if (deletionCandidates.length === 0) {
    lines.push("_None — every full template has at least one root where it is not exactly a close voicing._");
  } else {
    for (const c of deletionCandidates) lines.push(c);
  }
  lines.push("");
  lines.push("## Appendix — script");
  lines.push("");
  lines.push("Source: `scripts/audit-full-close-overlap.ts` in the same commit as this report.");
  lines.push("");

  return lines.join("\n");
}

import { writeFileSync } from "node:fs";
import { resolve } from "node:path";

const OUTPUT_PATH = resolve(
  import.meta.dirname ?? __dirname,
  "../docs/superpowers/research/2026-05-26-full-close-voicing-overlap.md",
);

it("audit-full-close-overlap", () => {
  const report = buildReport();
  writeFileSync(OUTPUT_PATH, report, "utf-8");
  console.log(`Report written to ${OUTPUT_PATH}`);
});
