#!/bin/sh

changed_files="$(git diff-tree -r --name-only --no-commit-id ORIG_HEAD HEAD)"
if echo "$changed_files" | grep --quiet "package-lock.json"; then
  echo "package-lock.json changed, running npm install..."
  npm install
fi
